# Project Context - Rust
# Migration: Node.js/Puppeteer → Rust/chromiumoxide
# This file contains project-specific configuration.
# Behavior protocols are hardcoded in the asimov binary.

identity:
  name: "ref"
  type: rust
  version: "0.1.0"
  tagline: "Reference verification tools with headless Chrome"

quality:
  test: "cargo test"
  lint: "cargo clippy -- -D warnings"
  format: "cargo fmt --check"
  build: "cargo build --release"

files:
  source:
    - "src/main.rs - Entry point"
    - "src/lib.rs - Library root"
  config:
    - "Cargo.toml - Dependencies and metadata"
  docs:
    - "README.md - Project documentation"

patterns:
  - "Result<T, E> for errors, no panics"
  - "thiserror for custom errors"
  - "No unwrap() in library code"
  - "Use clippy lints as errors"

release:
  profile: |
    [profile.release]
    opt-level = 3
    lto = true
    codegen-units = 1
    strip = true
    panic = "abort"
  compression: "UPX --best --lzma (optional)"

# v9.3.0: Coding standards for Rust projects (ADR-041)
coding_standards:
  code:
    file_size:
      soft_limit: 1000
      hard_limit: 1500
      note: "lines per file - split if exceeding"
    coverage: "100%"
    linting: "clippy pedantic, zero warnings"
    tests: "colocated with code (#[cfg(test)] mod tests)"
    formatting: "rustfmt (cargo fmt)"
  documentation:
    linting: "markdownlint-cli2"
    style:
      - "ATX-style headers (#)"
      - "One sentence per line (for git diffs)"
  architecture:
    decisions: "ADR format in docs/adr/"
    diagrams: "Mermaid preferred (text-based, version controlled)"

# v8.8.0: Standard deliverables for coding projects (ADR-034)
deliverables_template:
  - "[ ] Unit tests pass"
  - "[ ] E2E tests pass (if applicable)"
  - "[ ] cargo clippy -- -D warnings (zero warnings)"
  - "[ ] Update README if needed"
  - "[ ] Update --help if CLI"
  - "[ ] Commit and push"
  - "[ ] GitHub release (if applicable)"
